package io.youka.logparser.utils

import java.util.*

/**
 * API to get entries from resource **project.properties** (normally generated by build system).
 *
 * @author Christoph Spanknebel
 */
object ProjectProperties {
    /** Project name */
    val name: String
    /** Project version */
    val version: String
    /** Project description */
    val description: String
    /** Organization behind project */
    val organization: String
    /** Year of last project update */
    val year: String

    // Initialization
    init {
        // Load properties from file
        val props = Properties()
        this.javaClass.getResourceAsStream("/project.properties")?.use { stream -> props.load(stream) }
        // Assign property values
        name = props.getProperty("name") ?: ""
        version = props.getProperty("version") ?: ""
        description = props.getProperty("description") ?: ""
        organization = props.getProperty("organization") ?: ""
        year = props.getProperty("year") ?: ""
    }
}